#pragma once

enum PacketIds {
    ID_NEW_HOST = 50,
    ID_ASSIGNED_COLOR,
    ID_QUERY_HOSTS,
    ID_HOST_LIST,
    ID_JOIN_GAME,
    ID_HOST_STILL_GOOD,
    ID_READY_TO_ROLL,

    ID_SEND_INPUT,
    ID_RECEIVE_INPUT,
    ID_KILL_HAPPENED
};